version: "2"

services:
    mha_share:
        image: debian:jessie
        volumes:
            - "./docker_mha_share/:/mha_share/"
    mha_node:
        build: ./docker_mha_node
        image: vio/mha_node:1.0
        read_only: true
        environment:
            - MYSQL_ROOT_PASSWORD=123456
    mha_manager:
        build: ./docker_mha_manager
        image: vio/mha_manager:1.0
        read_only: true
    master:
        image: vio/mha_node:1.0
        depends_on:
            - mha_node
        ports:
            - "3406:3306"
        volumes:
            - "./init_db_scripts/:/docker-entrypoint-initdb.d/"
            - "./mha_master/lib/:/var/lib/mysql/"
            - "./mha_master/log/:/var/log/mysql/"
            - "./mha_master/conf.d/:/etc/mysql/mysql.conf.d/"
        volumes_from:
            - mha_share
        env_file:
            - ./account.env
        entrypoint:
            - /preparation/mysql_daemon.sh
    slave_1:
        image: vio/mha_node:1.0
        depends_on:
            - master
        ports:
            - "3407:3306"
        volumes:
            - "./mha_slave_1/lib/:/var/lib/mysql/"
            - "./mha_slave_1/log/:/var/log/mysql/"
            - "./mha_slave_1/conf.d/:/etc/mysql/mysql.conf.d/"
        volumes_from:
            - mha_share
        env_file:
            - ./account.env
        entrypoint:
            - /preparation/mysql_daemon.sh
    manager:
        image: vio/mha_manager:1.0
        depends_on:
            - mha_manager
            - slave_1
        ports:
            - "3506:3506"
        volumes:
            - "./mha_manager/log/:/var/log/masterha"
        volumes_from:
            - mha_share
        entrypoint:
            tailf /dev/null
        env_file:
            - ./account.env
